//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[
        ///   {
        ///      &quot;SequenceOne&quot;:
        ///         [
        ///            {
        ///               &quot;A&quot;: 123,
        ///               &quot;B&quot;: &quot;Some Value&quot;
        ///            },
        ///            {
        ///               &quot;A&quot;: 586,
        ///               &quot;B&quot;: &quot;Another Value&quot;
        ///            }
        ///         ],
        ///      &quot;Books&quot;: [ ]
        ///   }
        ///].
        /// </summary>
        internal static string JsonFile1 {
            get {
                return ResourceManager.GetString("JsonFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Books&quot;:
        ///         [ 
        ///            {
        ///    &quot;ISBN&quot;: &quot;978-0-361-11025-8&quot;,
        ///    &quot;author&quot;: &quot;Dena Todd&quot;,
        ///    &quot;Title&quot;: &quot;Tempor duis qui nostrud occaecat culpa labore dolor laborum do. Tempor incididunt ex ut culpa dolor qui amet id adipisicing. Incididunt aliqua eu deserunt anim dolor. Veniam qui tempor qui velit est Lorem reprehenderit anim commodo labore.\r\n&quot;,
        ///    &quot;Year&quot;: 2013,
        ///    &quot;publisher&quot;: &quot;Zolarex&quot;,
        ///    &quot;cost&quot;: 10.2201
        ///  },
        ///  {
        ///    &quot;ISBN&quot;: &quot;978-0-321-65870-8&quot;,
        ///    &quot;author&quot;: &quot;Mattie  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonFile3 {
            get {
                return ResourceManager.GetString("JsonFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;SequenceOne&quot;:
        ///         [
        ///            {
        ///               &quot;A&quot;: 123,
        ///               &quot;B&quot;: &quot;Some Value&quot;,
        ///               &quot;C&quot;: 154.844
        ///            },
        ///            {
        ///               &quot;A&quot;: 586,
        ///               &quot;B&quot;: &quot;Another Value&quot;,
        ///               &quot;C&quot;: 569.21
        ///            }
        ///         ],
        ///      &quot;Books&quot;:
        ///         [ ]
        ///   }
        ///].
        /// </summary>
        internal static string JsonFile4 {
            get {
                return ResourceManager.GetString("JsonFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;SequenceOne&quot;:
        ///         [
        ///            {
        ///               &quot;A&quot;: 123,
        ///               &quot;B&quot;: &quot;Some Value&quot;
        ///            },
        ///            {
        ///               &quot;A&quot;: 586,
        ///               &quot;B&quot;: &quot;Another Value&quot;
        ///            }
        ///         ],
        ///      &quot;SequenceTwo&quot;:
        ///         [
        ///            {
        ///               &quot;C&quot;: 258,
        ///               &quot;D&quot;: &quot;ASQR&quot;
        ///            },
        ///            {
        ///               &quot;C&quot;: 1024,
        ///               &quot;D&quot;: &quot;ABCD&quot;
        ///            }
        ///         ],
        ///      &quot;Books&quot;:
        ///         [
        ///            {
        ///    &quot;ISBN&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonFile5 {
            get {
                return ResourceManager.GetString("JsonFile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;RenamedProperty&quot;:
        ///         [
        ///            {
        ///               &quot;A&quot;: 123,
        ///               &quot;B&quot;: &quot;Some Value&quot;
        ///            },
        ///            {
        ///               &quot;A&quot;: 586,
        ///               &quot;B&quot;: &quot;Another Value&quot;
        ///            }
        ///         ],
        ///      &quot;SequenceTwo&quot;:
        ///         [
        ///            {
        ///               &quot;C&quot;: 258,
        ///               &quot;D&quot;: &quot;ASQR&quot;
        ///            },
        ///            {
        ///               &quot;C&quot;: 1024,
        ///               &quot;D&quot;: &quot;ABCD&quot;
        ///            }
        ///         ],
        ///      &quot;Books&quot;: []
        ///   }
        ///].
        /// </summary>
        internal static string JsonFile6 {
            get {
                return ResourceManager.GetString("JsonFile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///   {
        ///      &quot;Books&quot;:
        ///         [ ],
        ///      &quot;SequenceOne&quot;:
        ///         [
        ///            {
        ///               &quot;A&quot;: 123,
        ///               &quot;B&quot;: &quot;Some Value&quot;
        ///            },
        ///            {
        ///               &quot;A&quot;: 586,
        ///               &quot;B&quot;: &quot;Another Value&quot;
        ///            }
        ///         ]
        ///   }
        ///].
        /// </summary>
        internal static string JsonFille2 {
            get {
                return ResourceManager.GetString("JsonFille2", resourceCulture);
            }
        }
    }
}
